### ISSUE TITLE
lookup workspace from bucket?

### ISSUE THREAD

**Issue by eddiebroad** [broadinstitute/fiss#1]
I have found myself often trying to answer the question "I have a bucket, which workspace, does it belong to?"

To answer the question, I use a fissfc-based script and some greps to find the workspace for the bucket.

But I've asked the question so often, I wonder if it's a good idea for fissfc to have it as a use-case?

**Comment by tmdefreitas** [comment]
I've added a `space_search` command for this purpose. As a first pass, the only search criteria available is the bucket, but can be extended to search other fields.

Usage:

```
$ fissfc space_search -b 7f4211
kc_test_gistic2/broad-dsde-firecloud-billing

$fissfc space_search -b fc-a
Workspace	bucket
broad-dsde-firecloud-billing/kc_test_gistic2	fc-a7f4211d-3563-424c-9db7-c5f792563cd9
broad-firecloud-tcga/TCGA_LGG_OpenAccess_V1-0_DATA	fc-a846fd90-efcb-4439-b0fd-b0936758bc71
broad-firecloud-testing/API_TEST	fc-ad9ff181-a2c7-4b66-89a1-82657b77fe1e

```

**Comment by tmdefreitas** [comment]
This will be released alongside the API changes with the next FireCloud release in a few days
