### ISSUE TITLE
Urgent:  review and possibly change wrappers for RESTful FC apis

### ISSUE THREAD

**Issue by noblem** [broadinstitute/fiss#112]
Per email from Ilyana Rosenberg on Nov 1:

My team has been working on a new identity access management service that allows for increased flexibility in permissions and sharing across all of our back-end services as well as front-end applications. As part of the launch of this service to production, there have been a few modifications to previously existing APIs.

It looks like FISS has called these endpoints at least once in the past 6 months. Please review the [list of changes](https://docs.google.com/document/d/1TrycZszT2So9IYrvVjPAsIEhaLC7kp7dDVO2SdKU-70/edit) and make the appropriate API changes to ensure you are not impacted once the production changes are released at the end of the month.

**Comment by gsaksena** [comment]
Eric Jones commented on this relative to the Firehose to Firecloud project:

> These APIs all deal with group manipulation and we don't really do any of
that in FH2FC.  I think we're OK

**Comment by noblem** [comment]
Thanks Gordon.  Yeah, that's largely my take, but still we have due diligence to perform; and Ilyana did point out that FISS does call some of the endpoints to be changed.

**Comment by dheiman** [comment]
Reviewed, nothing for us to do.
