### ISSUE TITLE
Feature request - mop by file suffix

### ISSUE THREAD

**Issue by bknisbac** [broadinstitute/fiss#116]
Hi, 
Could you please add the following options to `mop`:
1) delete only unreferenced files that have a specific suffix
2) delete all unreferenced files except those that have a specific suffix 

Thanks!

**Comment by noblem** [comment]
Good idea!  With last minute things to finish as the year winds down, and imminent holiday closing, this will probably not be done until Jan 2019, but thanks for suggestion.
