### ISSUE TITLE
Add `copyFilesWithPrefix` parameter to "clone workspace"

### ISSUE THREAD

**Issue by rtitle** [broadinstitute/fiss#131]
The clone API includes an optional param `copyFilesWithPrefix` which specifies a prefix of bucket objects to copy to the destination workspace (it is typically used for copying notebooks). For example usage see Terra UI code: https://github.com/DataBiosphere/terra-ui/blob/2a0c196c11c0cccea6dd26ef15f9323867038c5d/src/components/NewWorkspaceModal.js#L74

It would be great if FISS supported this option as well.

**Comment by dheiman** [comment]
Hi @rtitle, is there any way that this parameter could be added to the API swagger docs? It's difficult to match undocumented capabilities:
https://api.firecloud.org/#!/Workspaces/cloneWorkspace

**Comment by dheiman** [comment]
It appears @MatthewBemis updated broadinstitute/rawls#1014 with this functionality, but the [orchestration API docs](https://github.com/broadinstitute/firecloud-orchestration/blob/f3b2071dd1f0cc7e3a6e5e85a95f4da0b1dd9fd8/src/main/resources/swagger/api-docs.yaml#L2873) were not updated.

**Comment by rtitle** [comment]
Thanks @dheiman - we can make a Swagger update to Rawls and Orch and link the PR here.
