### ISSUE TITLE
Error 401

### ISSUE THREAD

**Issue by slowkow** [broadinstitute/fiss#134]
I ran `gcloud auth login` and followed the steps to authenticate.

Then I ran `fissfc meth_list` and got this:

```
Error 401: b'<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">\n<html><head><script src="https://jsagent.tcell.io/tcellagent.min.js" tcellappid="FCProd-EBOgM" tcellapikey="AQQBBAFLGLOxL7VE9IF9ESlLvCxD5Ykr_7xkQKq_rgn_P58IWjOhOzIh6p3aI4pTWaprlUw" tcellbaseurl="https://us.agent.tcell.insight.rapid7.com/api/v1"></script>\n<title>401 Unauthorized</title>\n</head><body>\n<h1>Unauthorized</h1>\n<p>This server could not verify that you\nare authorized to access the document\nrequested.  Either you supplied the wrong\ncredentials (e.g., bad password), or your\nbrowser doesn\'t understand how to supply\nthe credentials required.</p>\n<hr>\n<address>Apache Server at api.firecloud.org Port 443</address>\n</body></html>\n'
```

It seems there is a problem with authentication. Previously, this command worked OK. So, I don't know what changed and why it does not work anymore.

Could I please ask for any hints or tips about how to get this to work?

Thank you!

**Comment by dheiman** [comment]
Hi @slowkow,

We've alerted the Terra team to this issue, which is due to their latest release. They are currently working on a solution.

**Comment by dheiman** [comment]
This should now be fixed. See [PROD-267](https://broadworkbench.atlassian.net/browse/PROD-267) for any further updates.
