### ISSUE TITLE
get_workspace_config returns an improperly formed json, differs from Swagger call response

### ISSUE THREAD

**Issue by jason-cerrato** [broadinstitute/fiss#163]
Running the `get_workspace_config` fapi function returns a json that is ill-formed and won't be accepted by `update_workspace_config`, `overwrite_workspace_config`, or their respective Swagger API modules.
![Screen Shot 2021-08-13 at 3 38 23 PM](https://user-images.githubusercontent.com/45641912/129410666-df46537c-fc5c-4848-88d1-694e233346b3.png)

I copy-pasted the json response to the body of the [updateWorkspaceMethodConfig](https://api.firecloud.org/#/Method%20Configurations/updateWorkspaceMethodConfig) Swagger API module and edited the file path.
![Screen Shot 2021-08-13 at 3 45 03 PM](https://user-images.githubusercontent.com/45641912/129411033-44c9df3d-fcba-466a-9193-2a4b528afdb4.png)
![Screen Shot 2021-08-13 at 3 45 21 PM](https://user-images.githubusercontent.com/45641912/129411040-1ea621b2-ae7d-4ede-9c3c-8ec43e876fcc.png)

Interestingly enough, running the [getWorkspaceMethodConfig](https://api.firecloud.org/#/Method%20Configurations/getWorkspaceMethodConfig) Swagger API module, which is meant to be the equivalent of the `get_workspace_config` function, returns a properly formed json.
![Screen Shot 2021-08-13 at 3 47 40 PM](https://user-images.githubusercontent.com/45641912/129411304-27e087f1-781a-4d83-bb27-b5e46fac7ae0.png)
![Screen Shot 2021-08-13 at 3 47 51 PM](https://user-images.githubusercontent.com/45641912/129411318-a03ee4d6-47eb-415f-a388-8cbd16713963.png)

**Comment by dheiman** [comment]
Hi @jason-cerrato, if you take a look at [`firecloud.fiss.config_get`](https://github.com/broadinstitute/fiss/blob/2cfce1f6dc0c43f62c51e8a9296946b9990a76fa/firecloud/fiss.py#L678), you'll see that if you want to copy the string form of the json object for editing, it needs some reformatting.
`request_object.json()` returns a dict, so it's not a representation meant for copy/paste (it doesn't escape the quotes within quotes, hence the errors you see via direct copy/paste into swagger).

If you do:
```python
import json
r = fapi.get_workspace_config("dsp-comms-dev", "jc_testing", "dsp-comms-dev", "Validate-BAM")
json.dumps(r.json(), indent=4, separators=(',', ': '), sort_keys=True, ensure_ascii=False)
```

the JSON dict should still work if you simply modify it within the notebook and use FISS directly via `fapi.create_workspace_config()`
