### ISSUE TITLE
Consider removing pylint as a dependency of the `firecloud` package.

### ISSUE THREAD

**Issue by deflaux** [broadinstitute/fiss#168]
The `firecloud` package depends on pylint in both [requirements.txt](https://github.com/broadinstitute/fiss/blob/2cfce1f6dc0c43f62c51e8a9296946b9990a76fa/requirements.txt#L3) and [setup.py](https://github.com/broadinstitute/fiss/blob/2cfce1f6dc0c43f62c51e8a9296946b9990a76fa/setup.py#L151) but it appears to [only be used a build time](https://github.com/broadinstitute/fiss/search?q=pylint) to lint the code.

This dependency is causing a potential security vulnerability in packages that depend on `firecloud`. For example, see https://github.com/all-of-us/workbench-snippets/pull/70

Consider removing pylint as a dependency of the `firecloud` package or, at a minimum, remove the package version pin from `setup.py` so that users are not forced to downgrade to an old version of pylint.

**Comment by amstilp** [comment]
I am having the same issue. I am unable to install another necessary python package in my virtual environment because it requires `pylint>=2.0`. Please fix.
