### ISSUE TITLE
`import firecloud.api` broken in Python 3.10

### ISSUE THREAD

**Issue by amstilp** [broadinstitute/fiss#170]
Python 3.10 changed the `collections` module, which breaks the `firecloud/api.py` file.

In a new venv with Python 3.10.2:
```
python -m venv venv
source venv/bin/activate
pip install --upgrade pip
pip install firecloud
python -c 'import firecloud.api as fapi'
```

gives this error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/amstilp/venv310/lib/python3.10/site-packages/firecloud/api.py", line 16, in <module>
    from collections import Iterable
ImportError: cannot import name 'Iterable' from 'collections' (/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/collections/__init__.py)
```

`import firecloud.api as fapi` works without error in Python 3.9.10.

**Comment by DailyDreaming** [comment]
I'm also having this issue.  Seems like an easy fix.  Since FISS seems to no longer be maintained, I may just move off of the FISS dependency and call the API directly then.

**Comment by dheiman** [comment]
Fix is in the works, I'm the only maintainer, so there can be delays in
releases. Expect the fix early next week.
