### ISSUE TITLE
Cannot import Workspace class

### ISSUE THREAD

**Issue by rickymagner** [broadinstitute/fiss#172]
This issue is about the [Workspace](https://github.com/broadinstitute/fiss/blob/master/firecloud/workspace.py) class. Its initialization input for `api_url` defaults to `fapi.PROD_API_ROOT` where `fapi` is `firecloud.api` as usual. However, when trying to run

`from firecloud.workspace import Workspace`

I get the error: `AttributeError: module 'firecloud.api' has no attribute 'PROD_API_ROOT'`. 

I tried copying the code and substituting `https://api.firecloud.org/api` for the default, as hinted by the docstring, but this led to a `FireCloudServerError`. 

This was all done from inside a Terra notebook. Unsure of what the appropriate fix should be, but I imagine properly defining `PROD_API_ROOT` might be the desired solution.

**Comment by dheiman** [comment]
The Workspace class is legacy code from initial development of FISS that was never removed (likely due to unrealized plans for an eventual refactor). It is not currently used nor supported.
