### ISSUE TITLE
sset_loop failing when used with flow_start

### ISSUE THREAD

**Issue by dheiman** [broadinstitute/fiss#29]
When I try to use `sset_loop` in a workspace to run `flow_start`, the following occurs:
```
% fissfc sset_loop -w stddata_packaging -p nci-dheiman-b-org -n broadgdac flow_start --config Merge_CNV__unfiltered__snp6 

flow_start TCGA-ACC:
Starting Merge_CNV__unfiltered__snp6 on TCGA-ACC in nci-dheiman-b-org/stddata_packaging
Error: 'Namespace' object has no attribute 'cache'
```
Manually looping through each sample_set works though:
```bash
for sset in `fissfc sset_list -w stddata_packaging -p nci-dheiman-b-org`; do
    fissfc flow_start -w stddata_packaging -p nci-dheiman-b-org -n broadgdac -c Merge_CNV__snp6 -e $sset
done
```

**Comment by noblem** [comment]
Noted, and thanks for the report.  Your CLI looks pretty hairy ... have you considered using a config file?  

%  cat ~mnoble/.fissconfig

[DEFAULT]
#project=broad-firecloud-gdac
project=nci-mnoble-bi-org
workspace=dev
method_ns=broadgdac

**Comment by dheiman** [comment]
This ***was*** using a config file - it still complained when I didn't give those options.

**Comment by dheiman** [comment]
I may have previously been using an outdated version - now it's not requiring those options, but I still get the same failure:
```
% cat ~/.fissconfig 
[DEFAULT]
project=nci-dheiman-b-org
workspace=stddata_packaging
method_ns=broadgdac

% fissfc sset_loop -w stddata_packaging flow_start --config Merge_CNV__unfiltered__snp6

flow_start TCGA-ACC:
Starting Merge_CNV__unfiltered__snp6 on TCGA-ACC in nci-dheiman-b-org/stddata_packaging
Error: 'Namespace' object has no attribute 'cache'
```

**Comment by noblem** [comment]
Ok, I'd filed another bug #30 to capture the issue that the config file was not being honored--but will close it.

**Comment by noblem** [comment]
I fixed this for *flow_start* but a deeper problem remains in that the way args are parsed will in general make it either difficult or impossible for *sset_loop* to correctly set defaults for the commands it calls (as they would be set if invoked directly from the CLI)
