### ISSUE TITLE
implement high-level command tests

### ISSUE THREAD

**Issue by noblem** [broadinstitute/fiss#9]
Presently "make test" exercises the low-level FC api bindings, but none of the high-level commands are being exercised

**Comment by tmdefreitas** [comment]
Writing more tests now, but the basic pattern is in as of fa3ab198ee21ae4ece204f2663e069d5c6632670. Use `make test_fiss` to test the cli exclusively, `make test` now runs both api and cli tests.

**Comment by noblem** [comment]
Great!

**Comment by noblem** [comment]
The test_fiss target has been renamed test_cli, and more high-level tests are clearly needed, but there's enough there now to close this for now
