### ISSUE TITLE
Add LL entityQuery and replace HL calls to LL getEntitiesWithType with it

### ISSUE THREAD

**Issue by dheiman** [broadinstitute/fiss#97]
Per https://gatkforums.broadinstitute.org/gatk/discussion/comment/49250

**Comment by noblem** [comment]
This already exists in code:

https://github.com/broadinstitute/fiss/blob/33a7c670c1713e2a6f531c18a7cc43f1b9299883/firecloud/api.py#L418

and is used in the HL interface as well:

https://github.com/broadinstitute/fiss/blob/33a7c670c1713e2a6f531c18a7cc43f1b9299883/firecloud/fiss.py#L1498'

the latter of which (per my last commit) is now used for all HL __get_entities() calls:

https://github.com/broadinstitute/fiss/blob/33a7c670c1713e2a6f531c18a7cc43f1b9299883/firecloud/fiss.py#L254
